=== akshshar/xr-auditor/userfiles/compliance.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0.0">

<!-- definition of simple elements -->
<xs:element name="HOST" type="xs:string"/>
<xs:element name="VENDOR" type="xs:string"/>
<xs:element name="PRODUCT" type="xs:string"/>
<xs:element name="OS" type="xs:string"/>
<xs:element name="VERSION" type="xs:string"/>
<xs:element name="IPADDR" type="xs:string"/>
<xs:element name="DATE" type="xs:string"/>

<xs:element name="NAME" type="xs:string"/>
<xs:element name="REQUEST" type="xs:string"/>
<xs:element name="RESPONSE" type="xs:string"/>
<xs:element name="CHECKSUM" type="xs:string"/>
<xs:element name="CONTENT" type="xs:string"/>
<xs:element name="XRSHOW" type="xs:string"/>
<xs:element name="ADMINSHOW" type="xs:string"/>

<xs:attribute name="DATE">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9]:[0-9][0-9] [A-Z].*"/>
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>


<!-- definition of complex elements -->

<xs:element name="CMD">
  <xs:complexType>
    <xs:all>
        <xs:element ref="REQUEST"/>
        <xs:element ref="RESPONSE"/>
    </xs:all>
  </xs:complexType>
</xs:element>

<xs:element name="CMD-LIST">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="CMD"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="DIRECTORY">
  <xs:complexType>
    <xs:all>
      <xs:element ref="NAME"/>
      <xs:element ref="CMD-LIST" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:element>

<xs:element name="FILE">
  <xs:complexType>
    <xs:all>
        <xs:element ref="NAME"/>
        <xs:element ref="CMD-LIST" minOccurs="0"/>
        <xs:element ref="CHECKSUM" minOccurs="0"/>
        <xs:element ref="CONTENT" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:element>


<xs:element name="DIRECTORIES">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="DIRECTORY"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="FILES">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="FILE"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="XR">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="XRSHOW"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="XRADMIN">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ADMINSHOW"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="INTEGRITY">
  <xs:complexType>
    <xs:all>
        <xs:element ref="DIRECTORIES"/>
        <xs:element ref="FILES"/>
        <xs:element ref="XR" minOccurs="0"/>
        <xs:element ref="XRADMIN" minOccurs="0"/>
    </xs:all>
    <xs:attribute name="domain" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>


<xs:element name="GENERAL">
  <xs:complexType>
    <xs:all>
        <xs:element ref="HOST"/>
        <xs:element ref="DATE"/>
        <xs:element ref="VENDOR"/>
        <xs:element ref="PRODUCT"/>
        <xs:element ref="OS"/>
        <xs:element ref="VERSION"/>
        <xs:element ref="IPADDR"/>
    </xs:all>
  </xs:complexType>
</xs:element>




<xs:element name="COMPLIANCE-DUMP">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="INTEGRITY"/>
      <xs:element ref="GENERAL"/>
    </xs:sequence>
    <xs:attribute name="version" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

</xs:schema>

=== akshshar/xr-auditor/collector/XR-LXC.xml
<?xml version="1.0" encoding="utf-8"?>
<COMPLIANCE-DUMP version="1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compliance.xsd">
	<INTEGRITY domain="XR-LXC">
		<FILES>
			<FILE>
				<CHECKSUM>d7e4f42b44b3fb07df51498831ca70d4</CHECKSUM>
				<CMD-LIST>
					<CMD>
						<REQUEST>ls -la</REQUEST>
						<RESPONSE>-rwxr-xr-x 1 root root 3275 Apr  3 18:28 /etc/ssh/sshd_config
</RESPONSE>
					</CMD>
					<CMD>
						<REQUEST>ls -la</REQUEST>
						<RESPONSE>-rw-r--r-- 1 root root 954 Apr 10 01:59 /etc/passwd
</RESPONSE>
					</CMD>
				</CMD-LIST>
				<NAME>/etc/passwd</NAME>
			</FILE>
			<FILE>
				<CHECKSUM>d7e4f42b44b3fb07df51498831ca70d4</CHECKSUM>
				<CMD-LIST>
					<CMD>
						<REQUEST>ls -la</REQUEST>
						<RESPONSE>-rwxr-xr-x 1 root root 3275 Apr  3 18:28 /etc/ssh/sshd_config
</RESPONSE>
					</CMD>
					<CMD>
						<REQUEST>ls -la</REQUEST>
						<RESPONSE>-rw-r--r-- 1 root root 954 Apr 10 01:59 /etc/passwd
</RESPONSE>
					</CMD>
				</CMD-LIST>
				<NAME>/etc/passwd</NAME>
			</FILE>
		</FILES>
		<DIRECTORIES>
			<DIRECTORY>
				<CMD-LIST>
					<CMD>
						<REQUEST>ls -ld</REQUEST>
						<RESPONSE>drwxr-xr-x 3 root root 20480 Apr  3 18:28 /usr/bin
</RESPONSE>
					</CMD>
					<CMD>
						<REQUEST>ls -ld</REQUEST>
						<RESPONSE>drwxr-xr-x 4 root root 4096 Apr  3 18:28 /usr/lib
</RESPONSE>
					</CMD>
				</CMD-LIST>
				<NAME>/usr/lib</NAME>
			</DIRECTORY>
			<DIRECTORY>
				<CMD-LIST>
					<CMD>
						<REQUEST>ls -ld</REQUEST>
						<RESPONSE>drwxr-xr-x 3 root root 20480 Apr  3 18:28 /usr/bin
</RESPONSE>
					</CMD>
					<CMD>
						<REQUEST>ls -ld</REQUEST>
						<RESPONSE>drwxr-xr-x 4 root root 4096 Apr  3 18:28 /usr/lib
</RESPONSE>
					</CMD>
				</CMD-LIST>
				<NAME>/usr/lib</NAME>
			</DIRECTORY>
		</DIRECTORIES>
	</INTEGRITY>
	<GENERAL>
		<PRODUCT>NCS-5501</PRODUCT>
		<VENDOR>Cisco</VENDOR>
		<IPADDR>11.11.11.33/24</IPADDR>
		<HOST>rtr</HOST>
		<VERSION>6.1.31</VERSION>
		<DATE>20180412-15:07 UTC</DATE>
		<OS>IOS-XR</OS>
	</GENERAL>
</COMPLIANCE-DUMP>
